import { parser } from '../compiler/Parse';

let tokenizerOut = [
    { type: 'paren', value: '<' },
    { type: 'name', value: 'functionGlobalCSSMainparent' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'body' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'render' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'varMainparent' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'style' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'string' },
    {
        type: 'string',
        value: '\n.nav-button{\nbackground-color:#4CAF50;/*Green*/\nborder:none;\ncolor:white;\npadding:15px32px;\ntext-align:center;\ntext-decoration:none;\nfont-size:16px;\ncursor:pointer;\noutline:none;\n}\n.nav-button:hover{\nbackground-color:#3e8e41;\n}\nbody{\nborder:0;\n}\n.hidden_tag{\ndisplay:none;\n}\n/*Yikesthishandlesthesmalltext*/\n.downabit{\ntransform:translate(0,100%);\n}\n',
    },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'empty' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
];

let astOut = {
    type: 'Program',
    body: [
        {
            type: 'CallExpression',
            name: 'functionGlobalCSSMainparent',
            params: [
                {
                    type: 'CallExpression',
                    name: 'body',
                    params: [
                        {
                            type: 'CallExpression',
                            name: 'render',
                            params: [
                                { type: 'CallExpression', name: 'varMainparent', params: [] },
                                {
                                    type: 'CallExpression',
                                    name: 'style',
                                    params: [
                                        {
                                            type: 'CallExpression',
                                            name: 'string',
                                            params: [
                                                {
                                                    type: 'StringLiteral',
                                                    value: '\n.nav-button{\nbackground-color:#4CAF50;/*Green*/\nborder:none;\ncolor:white;\npadding:15px32px;\ntext-align:center;\ntext-decoration:none;\nfont-size:16px;\ncursor:pointer;\noutline:none;\n}\n.nav-button:hover{\nbackground-color:#3e8e41;\n}\nbody{\nborder:0;\n}\n.hidden_tag{\ndisplay:none;\n}\n/*Yikesthishandlesthesmalltext*/\n.downabit{\ntransform:translate(0,100%);\n}\n',
                                                },
                                            ],
                                        },
                                        { type: 'CallExpression', name: 'empty', params: [] },
                                    ],
                                },
                            ],
                        },
                    ],
                },
            ],
        },
    ],
};

let tokenInTwo = [
    { type: 'paren', value: '<' },
    { type: 'name', value: 'sayHello' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'string' },
    { type: 'name', value: 'hello' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'letsmake' },
    { type: 'name', value: 'TOKEN' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'string' },
    { type: 'string', value: 'TOKEN' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'letsmake' },
    { type: 'name', value: 'Discord' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'iNeed' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'string' },
    { type: 'string', value: 'discord.js' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'letsmake' },
    { type: 'name', value: 'client' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'new' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'call' },
    { type: 'name', value: 'Discord.Client' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'call' },
    { type: 'name', value: 'client.on' },
    { type: 'string', value: 'ready' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'function' },
    { type: 'name', value: 'data' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'body' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'sendOut' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'add' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'string' },
    { type: 'name', value: 'Current' },
    { type: 'name', value: 'Logged' },
    { type: 'name', value: 'in' },
    { type: 'name', value: 'as' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'var' },
    { type: 'name', value: 'client.user.username' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'string' },
    { type: 'string', value: '#' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'var' },
    { type: 'name', value: 'client.user.discriminator' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'sendOut' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'add' },
    { type: 'string', value: 'Current in ' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'var' },
    { type: 'name', value: 'client.guilds.cache.size' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'sring' },
    { type: 'name', value: 'servers' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'call' },
    { type: 'name', value: 'client.on' },
    { type: 'string', value: 'message' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'async' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'Arrowfunc' },
    { type: 'name', value: 'message' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'body' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'if' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'and' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'equal' },
    { type: 'name', value: 'message.content' },
    { type: 'string', value: 'hello' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'equal' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'ToNumber' },
    { type: 'name', value: 'message.author.bot' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'false' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'body' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'call' },
    { type: 'name', value: 'message.reply' },
    { type: 'string', value: 'hello' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'letsmake' },
    { type: 'name', value: 'functionIWant' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'Arrowfunc' },
    { type: 'name', value: 'input' },
    { type: 'name', value: 'secondInput' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'body' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'sendOut' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'var' },
    { type: 'name', value: 'input' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'sendOut' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'var' },
    { type: 'name', value: 'secondInput' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'letsmake' },
    { type: 'name', value: 'AsyncFunction' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'async' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'Arrowfunc' },
    { type: 'name', value: 'input' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'body' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'sendOut' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'var' },
    { type: 'name', value: 'input' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'call' },
    { type: 'name', value: 'functionIWant' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'string' },
    { type: 'string', value: 'hello' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'string' },
    { type: 'string', value: 'Second Input' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'call' },
    { type: 'name', value: 'AsyncFunction' },
    { type: 'string', value: 'async' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'after' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'Arrowfunc' },
    { type: 'name', value: 'input' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'body' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'sendOut' },
    { type: 'string', value: 'done' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'error' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'Arrowfunc' },
    { type: 'name', value: 'input' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'body' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'sendOut' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'add' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'string' },
    { type: 'string', value: 'There was a error ' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'var' },
    { type: 'name', value: 'input' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'letsmake' },
    { type: 'name', value: 'Newer' },
    { type: 'string', value: 'hello' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'function' },
    { type: 'name', value: 'hello' },
    { type: 'name', value: 'input' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'body' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'reply' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'var' },
    { type: 'name', value: 'input' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'letsmake' },
    { type: 'name', value: 'PromiseMaker' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'Arrowfunc' },
    { type: 'name', value: 'input' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'body' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'promise' },
    { type: 'name', value: 'resolve' },
    { type: 'name', value: 'reject' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'body' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'sendOut' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'var' },
    { type: 'name', value: 'input' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'if' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'equal' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'var' },
    { type: 'name', value: 'input' },
    { type: 'paren', value: '>' },
    { type: 'string', value: "'hello'" },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'body' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'call' },
    { type: 'name', value: 'reject' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'string' },
    { type: 'string', value: 'Not going to lie there is a errror' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'if' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'notequal' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'var' },
    { type: 'name', value: 'input' },
    { type: 'paren', value: '>' },
    { type: 'string', value: "'hello'" },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'body' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'call' },
    { type: 'name', value: 'resolve' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'letsmake' },
    { type: 'name', value: 'reponse' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'call' },
    { type: 'name', value: 'PromiseMaker' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'string' },
    { type: 'string', value: 'hello' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'error' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'Arrowfunc' },
    { type: 'name', value: 'input' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'body' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'sendOut' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'add' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'string' },
    { type: 'string', value: 'There was a error ' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'var' },
    { type: 'name', value: 'input' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'call' },
    { type: 'name', value: 'PromiseMaker' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'string' },
    { type: 'string', value: 'anything else' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'error' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'Arrowfunc' },
    { type: 'name', value: 'input' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'body' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'sendOut' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'add' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'string' },
    { type: 'string', value: 'There was a error ' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'var' },
    { type: 'name', value: 'input' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'after' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'Arrowfunc' },
    { type: 'name', value: 'input' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'body' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'sendOut' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'string' },
    { type: 'string', value: 'Promises successful' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'call' },
    { type: 'name', value: 'PromiseMaker' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'string' },
    { type: 'string', value: 'hello' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'after' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'Arrowfunc' },
    { type: 'name', value: 'input' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'body' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'sendOut' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'string' },
    { type: 'string', value: 'Promises successful' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'error' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'Arrowfunc' },
    { type: 'name', value: 'input' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'body' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'sendOut' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'add' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'string' },
    { type: 'string', value: 'There was a error ' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'var' },
    { type: 'name', value: 'input' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'call' },
    { type: 'name', value: 'client.login' },
    { type: 'paren', value: '<' },
    { type: 'name', value: 'var' },
    { type: 'name', value: 'TOKEN' },
    { type: 'paren', value: '>' },
    { type: 'paren', value: '>' },
];

let astTwoOut = {
    type: 'Program',
    body: [
        {
            type: 'CallExpression',
            name: 'sayHello',
            params: [{ type: 'CallExpression', name: 'string', params: [{ type: 'StringLiteral', value: 'hello' }] }],
        },
        {
            type: 'CallExpression',
            name: 'letsmake',
            params: [
                { type: 'StringLiteral', value: 'TOKEN' },
                { type: 'CallExpression', name: 'string', params: [{ type: 'StringLiteral', value: 'TOKEN' }] },
            ],
        },
        {
            type: 'CallExpression',
            name: 'letsmake',
            params: [
                { type: 'StringLiteral', value: 'Discord' },
                {
                    type: 'CallExpression',
                    name: 'iNeed',
                    params: [
                        {
                            type: 'CallExpression',
                            name: 'string',
                            params: [{ type: 'StringLiteral', value: 'discord.js' }],
                        },
                    ],
                },
            ],
        },
        {
            type: 'CallExpression',
            name: 'letsmake',
            params: [
                { type: 'StringLiteral', value: 'client' },
                {
                    type: 'CallExpression',
                    name: 'new',
                    params: [
                        {
                            type: 'CallExpression',
                            name: 'call',
                            params: [{ type: 'StringLiteral', value: 'Discord.Client' }],
                        },
                    ],
                },
            ],
        },
        {
            type: 'CallExpression',
            name: 'call',
            params: [
                { type: 'StringLiteral', value: 'client.on' },
                { type: 'StringLiteral', value: 'ready' },
                {
                    type: 'CallExpression',
                    name: 'function',
                    params: [
                        { type: 'StringLiteral', value: 'data' },
                        {
                            type: 'CallExpression',
                            name: 'body',
                            params: [
                                {
                                    type: 'CallExpression',
                                    name: 'sendOut',
                                    params: [
                                        {
                                            type: 'CallExpression',
                                            name: 'add',
                                            params: [
                                                {
                                                    type: 'CallExpression',
                                                    name: 'string',
                                                    params: [
                                                        { type: 'StringLiteral', value: 'Current' },
                                                        { type: 'StringLiteral', value: 'Logged' },
                                                        { type: 'StringLiteral', value: 'in' },
                                                        { type: 'StringLiteral', value: 'as' },
                                                    ],
                                                },
                                                {
                                                    type: 'CallExpression',
                                                    name: 'var',
                                                    params: [{ type: 'StringLiteral', value: 'client.user.username' }],
                                                },
                                                {
                                                    type: 'CallExpression',
                                                    name: 'string',
                                                    params: [{ type: 'StringLiteral', value: '#' }],
                                                },
                                                {
                                                    type: 'CallExpression',
                                                    name: 'var',
                                                    params: [
                                                        { type: 'StringLiteral', value: 'client.user.discriminator' },
                                                    ],
                                                },
                                            ],
                                        },
                                    ],
                                },
                                {
                                    type: 'CallExpression',
                                    name: 'sendOut',
                                    params: [
                                        {
                                            type: 'CallExpression',
                                            name: 'add',
                                            params: [
                                                { type: 'StringLiteral', value: 'Current in ' },
                                                {
                                                    type: 'CallExpression',
                                                    name: 'var',
                                                    params: [
                                                        { type: 'StringLiteral', value: 'client.guilds.cache.size' },
                                                        {
                                                            type: 'CallExpression',
                                                            name: 'sring',
                                                            params: [{ type: 'StringLiteral', value: 'servers' }],
                                                        },
                                                    ],
                                                },
                                            ],
                                        },
                                    ],
                                },
                            ],
                        },
                    ],
                },
            ],
        },
        {
            type: 'CallExpression',
            name: 'call',
            params: [
                { type: 'StringLiteral', value: 'client.on' },
                { type: 'StringLiteral', value: 'message' },
                {
                    type: 'CallExpression',
                    name: 'async',
                    params: [
                        {
                            type: 'CallExpression',
                            name: 'Arrowfunc',
                            params: [
                                { type: 'StringLiteral', value: 'message' },
                                {
                                    type: 'CallExpression',
                                    name: 'body',
                                    params: [
                                        {
                                            type: 'CallExpression',
                                            name: 'if',
                                            params: [
                                                {
                                                    type: 'CallExpression',
                                                    name: 'and',
                                                    params: [
                                                        {
                                                            type: 'CallExpression',
                                                            name: 'equal',
                                                            params: [
                                                                { type: 'StringLiteral', value: 'message.content' },
                                                                { type: 'StringLiteral', value: 'hello' },
                                                            ],
                                                        },
                                                        {
                                                            type: 'CallExpression',
                                                            name: 'equal',
                                                            params: [
                                                                {
                                                                    type: 'CallExpression',
                                                                    name: 'ToNumber',
                                                                    params: [
                                                                        {
                                                                            type: 'StringLiteral',
                                                                            value: 'message.author.bot',
                                                                        },
                                                                    ],
                                                                },
                                                                { type: 'CallExpression', name: 'false', params: [] },
                                                            ],
                                                        },
                                                    ],
                                                },
                                                {
                                                    type: 'CallExpression',
                                                    name: 'body',
                                                    params: [
                                                        {
                                                            type: 'CallExpression',
                                                            name: 'call',
                                                            params: [
                                                                { type: 'StringLiteral', value: 'message.reply' },
                                                                { type: 'StringLiteral', value: 'hello' },
                                                            ],
                                                        },
                                                    ],
                                                },
                                            ],
                                        },
                                    ],
                                },
                            ],
                        },
                    ],
                },
            ],
        },
        {
            type: 'CallExpression',
            name: 'letsmake',
            params: [
                { type: 'StringLiteral', value: 'functionIWant' },
                {
                    type: 'CallExpression',
                    name: 'Arrowfunc',
                    params: [
                        { type: 'StringLiteral', value: 'input' },
                        { type: 'StringLiteral', value: 'secondInput' },
                        {
                            type: 'CallExpression',
                            name: 'body',
                            params: [
                                {
                                    type: 'CallExpression',
                                    name: 'sendOut',
                                    params: [
                                        {
                                            type: 'CallExpression',
                                            name: 'var',
                                            params: [{ type: 'StringLiteral', value: 'input' }],
                                        },
                                    ],
                                },
                                {
                                    type: 'CallExpression',
                                    name: 'sendOut',
                                    params: [
                                        {
                                            type: 'CallExpression',
                                            name: 'var',
                                            params: [{ type: 'StringLiteral', value: 'secondInput' }],
                                        },
                                    ],
                                },
                            ],
                        },
                    ],
                },
            ],
        },
        {
            type: 'CallExpression',
            name: 'letsmake',
            params: [
                { type: 'StringLiteral', value: 'AsyncFunction' },
                {
                    type: 'CallExpression',
                    name: 'async',
                    params: [
                        {
                            type: 'CallExpression',
                            name: 'Arrowfunc',
                            params: [
                                { type: 'StringLiteral', value: 'input' },
                                {
                                    type: 'CallExpression',
                                    name: 'body',
                                    params: [
                                        {
                                            type: 'CallExpression',
                                            name: 'sendOut',
                                            params: [
                                                {
                                                    type: 'CallExpression',
                                                    name: 'var',
                                                    params: [{ type: 'StringLiteral', value: 'input' }],
                                                },
                                            ],
                                        },
                                    ],
                                },
                            ],
                        },
                    ],
                },
            ],
        },
        {
            type: 'CallExpression',
            name: 'call',
            params: [
                { type: 'StringLiteral', value: 'functionIWant' },
                { type: 'CallExpression', name: 'string', params: [{ type: 'StringLiteral', value: 'hello' }] },
                { type: 'CallExpression', name: 'string', params: [{ type: 'StringLiteral', value: 'Second Input' }] },
            ],
        },
        {
            type: 'CallExpression',
            name: 'call',
            params: [
                { type: 'StringLiteral', value: 'AsyncFunction' },
                { type: 'StringLiteral', value: 'async' },
            ],
        },
        {
            type: 'CallExpression',
            name: 'after',
            params: [
                {
                    type: 'CallExpression',
                    name: 'Arrowfunc',
                    params: [
                        { type: 'StringLiteral', value: 'input' },
                        {
                            type: 'CallExpression',
                            name: 'body',
                            params: [
                                {
                                    type: 'CallExpression',
                                    name: 'sendOut',
                                    params: [{ type: 'StringLiteral', value: 'done' }],
                                },
                            ],
                        },
                    ],
                },
            ],
        },
        {
            type: 'CallExpression',
            name: 'error',
            params: [
                {
                    type: 'CallExpression',
                    name: 'Arrowfunc',
                    params: [
                        { type: 'StringLiteral', value: 'input' },
                        {
                            type: 'CallExpression',
                            name: 'body',
                            params: [
                                {
                                    type: 'CallExpression',
                                    name: 'sendOut',
                                    params: [
                                        {
                                            type: 'CallExpression',
                                            name: 'add',
                                            params: [
                                                {
                                                    type: 'CallExpression',
                                                    name: 'string',
                                                    params: [{ type: 'StringLiteral', value: 'There was a error ' }],
                                                },
                                                {
                                                    type: 'CallExpression',
                                                    name: 'var',
                                                    params: [{ type: 'StringLiteral', value: 'input' }],
                                                },
                                            ],
                                        },
                                    ],
                                },
                            ],
                        },
                    ],
                },
            ],
        },
        {
            type: 'CallExpression',
            name: 'letsmake',
            params: [
                { type: 'StringLiteral', value: 'Newer' },
                { type: 'StringLiteral', value: 'hello' },
            ],
        },
        {
            type: 'CallExpression',
            name: 'function',
            params: [
                { type: 'StringLiteral', value: 'hello' },
                { type: 'StringLiteral', value: 'input' },
                {
                    type: 'CallExpression',
                    name: 'body',
                    params: [
                        {
                            type: 'CallExpression',
                            name: 'reply',
                            params: [
                                {
                                    type: 'CallExpression',
                                    name: 'var',
                                    params: [{ type: 'StringLiteral', value: 'input' }],
                                },
                            ],
                        },
                    ],
                },
            ],
        },
        {
            type: 'CallExpression',
            name: 'letsmake',
            params: [
                { type: 'StringLiteral', value: 'PromiseMaker' },
                {
                    type: 'CallExpression',
                    name: 'Arrowfunc',
                    params: [
                        { type: 'StringLiteral', value: 'input' },
                        {
                            type: 'CallExpression',
                            name: 'body',
                            params: [
                                {
                                    type: 'CallExpression',
                                    name: 'promise',
                                    params: [
                                        { type: 'StringLiteral', value: 'resolve' },
                                        { type: 'StringLiteral', value: 'reject' },
                                        {
                                            type: 'CallExpression',
                                            name: 'body',
                                            params: [
                                                {
                                                    type: 'CallExpression',
                                                    name: 'sendOut',
                                                    params: [
                                                        {
                                                            type: 'CallExpression',
                                                            name: 'var',
                                                            params: [{ type: 'StringLiteral', value: 'input' }],
                                                        },
                                                    ],
                                                },
                                                {
                                                    type: 'CallExpression',
                                                    name: 'if',
                                                    params: [
                                                        {
                                                            type: 'CallExpression',
                                                            name: 'equal',
                                                            params: [
                                                                {
                                                                    type: 'CallExpression',
                                                                    name: 'var',
                                                                    params: [{ type: 'StringLiteral', value: 'input' }],
                                                                },
                                                                { type: 'StringLiteral', value: "'hello'" },
                                                            ],
                                                        },
                                                        {
                                                            type: 'CallExpression',
                                                            name: 'body',
                                                            params: [
                                                                {
                                                                    type: 'CallExpression',
                                                                    name: 'call',
                                                                    params: [
                                                                        { type: 'StringLiteral', value: 'reject' },
                                                                        {
                                                                            type: 'CallExpression',
                                                                            name: 'string',
                                                                            params: [
                                                                                {
                                                                                    type: 'StringLiteral',
                                                                                    value: 'Not going to lie there is a errror',
                                                                                },
                                                                            ],
                                                                        },
                                                                    ],
                                                                },
                                                            ],
                                                        },
                                                    ],
                                                },
                                                {
                                                    type: 'CallExpression',
                                                    name: 'if',
                                                    params: [
                                                        {
                                                            type: 'CallExpression',
                                                            name: 'notequal',
                                                            params: [
                                                                {
                                                                    type: 'CallExpression',
                                                                    name: 'var',
                                                                    params: [{ type: 'StringLiteral', value: 'input' }],
                                                                },
                                                                { type: 'StringLiteral', value: "'hello'" },
                                                            ],
                                                        },
                                                        {
                                                            type: 'CallExpression',
                                                            name: 'body',
                                                            params: [
                                                                {
                                                                    type: 'CallExpression',
                                                                    name: 'call',
                                                                    params: [
                                                                        { type: 'StringLiteral', value: 'resolve' },
                                                                    ],
                                                                },
                                                            ],
                                                        },
                                                    ],
                                                },
                                            ],
                                        },
                                    ],
                                },
                            ],
                        },
                    ],
                },
            ],
        },
        {
            type: 'CallExpression',
            name: 'letsmake',
            params: [
                { type: 'StringLiteral', value: 'reponse' },
                {
                    type: 'CallExpression',
                    name: 'call',
                    params: [
                        { type: 'StringLiteral', value: 'PromiseMaker' },
                        { type: 'CallExpression', name: 'string', params: [{ type: 'StringLiteral', value: 'hello' }] },
                    ],
                },
            ],
        },
        {
            type: 'CallExpression',
            name: 'error',
            params: [
                {
                    type: 'CallExpression',
                    name: 'Arrowfunc',
                    params: [
                        { type: 'StringLiteral', value: 'input' },
                        {
                            type: 'CallExpression',
                            name: 'body',
                            params: [
                                {
                                    type: 'CallExpression',
                                    name: 'sendOut',
                                    params: [
                                        {
                                            type: 'CallExpression',
                                            name: 'add',
                                            params: [
                                                {
                                                    type: 'CallExpression',
                                                    name: 'string',
                                                    params: [{ type: 'StringLiteral', value: 'There was a error ' }],
                                                },
                                                {
                                                    type: 'CallExpression',
                                                    name: 'var',
                                                    params: [{ type: 'StringLiteral', value: 'input' }],
                                                },
                                            ],
                                        },
                                    ],
                                },
                            ],
                        },
                    ],
                },
            ],
        },
        {
            type: 'CallExpression',
            name: 'call',
            params: [
                { type: 'StringLiteral', value: 'PromiseMaker' },
                { type: 'CallExpression', name: 'string', params: [{ type: 'StringLiteral', value: 'anything else' }] },
            ],
        },
        {
            type: 'CallExpression',
            name: 'error',
            params: [
                {
                    type: 'CallExpression',
                    name: 'Arrowfunc',
                    params: [
                        { type: 'StringLiteral', value: 'input' },
                        {
                            type: 'CallExpression',
                            name: 'body',
                            params: [
                                {
                                    type: 'CallExpression',
                                    name: 'sendOut',
                                    params: [
                                        {
                                            type: 'CallExpression',
                                            name: 'add',
                                            params: [
                                                {
                                                    type: 'CallExpression',
                                                    name: 'string',
                                                    params: [{ type: 'StringLiteral', value: 'There was a error ' }],
                                                },
                                                {
                                                    type: 'CallExpression',
                                                    name: 'var',
                                                    params: [{ type: 'StringLiteral', value: 'input' }],
                                                },
                                            ],
                                        },
                                    ],
                                },
                            ],
                        },
                    ],
                },
            ],
        },
        {
            type: 'CallExpression',
            name: 'after',
            params: [
                {
                    type: 'CallExpression',
                    name: 'Arrowfunc',
                    params: [
                        { type: 'StringLiteral', value: 'input' },
                        {
                            type: 'CallExpression',
                            name: 'body',
                            params: [
                                {
                                    type: 'CallExpression',
                                    name: 'sendOut',
                                    params: [
                                        {
                                            type: 'CallExpression',
                                            name: 'string',
                                            params: [{ type: 'StringLiteral', value: 'Promises successful' }],
                                        },
                                    ],
                                },
                            ],
                        },
                    ],
                },
            ],
        },
        {
            type: 'CallExpression',
            name: 'call',
            params: [
                { type: 'StringLiteral', value: 'PromiseMaker' },
                { type: 'CallExpression', name: 'string', params: [{ type: 'StringLiteral', value: 'hello' }] },
            ],
        },
        {
            type: 'CallExpression',
            name: 'after',
            params: [
                {
                    type: 'CallExpression',
                    name: 'Arrowfunc',
                    params: [
                        { type: 'StringLiteral', value: 'input' },
                        {
                            type: 'CallExpression',
                            name: 'body',
                            params: [
                                {
                                    type: 'CallExpression',
                                    name: 'sendOut',
                                    params: [
                                        {
                                            type: 'CallExpression',
                                            name: 'string',
                                            params: [{ type: 'StringLiteral', value: 'Promises successful' }],
                                        },
                                    ],
                                },
                            ],
                        },
                    ],
                },
            ],
        },
        {
            type: 'CallExpression',
            name: 'error',
            params: [
                {
                    type: 'CallExpression',
                    name: 'Arrowfunc',
                    params: [
                        { type: 'StringLiteral', value: 'input' },
                        {
                            type: 'CallExpression',
                            name: 'body',
                            params: [
                                {
                                    type: 'CallExpression',
                                    name: 'sendOut',
                                    params: [
                                        {
                                            type: 'CallExpression',
                                            name: 'add',
                                            params: [
                                                {
                                                    type: 'CallExpression',
                                                    name: 'string',
                                                    params: [{ type: 'StringLiteral', value: 'There was a error ' }],
                                                },
                                                {
                                                    type: 'CallExpression',
                                                    name: 'var',
                                                    params: [{ type: 'StringLiteral', value: 'input' }],
                                                },
                                            ],
                                        },
                                    ],
                                },
                            ],
                        },
                    ],
                },
            ],
        },
        {
            type: 'CallExpression',
            name: 'call',
            params: [
                { type: 'StringLiteral', value: 'client.login' },
                { type: 'CallExpression', name: 'var', params: [{ type: 'StringLiteral', value: 'TOKEN' }] },
            ],
        },
    ],
};

test('Parser, Web Harvscript', () => {
    expect(parser(tokenizerOut)).toStrictEqual(astOut);
});

test('Parser, Standard Harvscript', () => {
    expect(parser(tokenInTwo)).toStrictEqual(astTwoOut);
});
